"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-09-25 21:07:56.618571

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "brands",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("normalized_name", sa.String(length=200), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_brands")),
        sa.UniqueConstraint("normalized_name", name=op.f("uq_brands_normalized_name")),
    )
    op.create_table(
        "retailers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("domain", sa.String(length=200), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_retailers")),
        sa.UniqueConstraint("domain", name=op.f("uq_retailers_domain")),
        sa.UniqueConstraint("slug", name=op.f("uq_retailers_slug")),
    )
    op.create_table(
        "products",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("brand_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("normalized_name", sa.String(length=500), nullable=False),
        sa.Column("size_value", sa.Numeric(precision=10, scale=3), nullable=True),
        sa.Column("size_unit", sa.String(length=10), nullable=True),
        sa.Column("ean", sa.String(length=14), nullable=True),
        sa.Column("category", sa.String(length=200), nullable=True),
        sa.Column("image_url", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "size_unit IS NULL OR size_unit IN ('ml', 'l', 'g', 'kg', 'buc')",
            name=op.f("ck_products_size_unit_known"),
        ),
        sa.CheckConstraint(
            "size_value IS NULL OR size_value > 0", name=op.f("ck_products_size_value_positive")
        ),
        sa.ForeignKeyConstraint(
            ["brand_id"],
            ["brands.id"],
            name=op.f("fk_products_brand_id_brands"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_products")),
        sa.UniqueConstraint("ean", name=op.f("uq_products_ean")),
    )
    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_products_brand_id"), ["brand_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_products_normalized_name"), ["normalized_name"], unique=False
        )

    op.create_table(
        "offers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("retailer_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=True),
        sa.Column("url", sa.String(length=2000), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("brand_name", sa.String(length=200), nullable=True),
        sa.Column("ean", sa.String(length=14), nullable=True),
        sa.Column("size_value", sa.Numeric(precision=10, scale=3), nullable=True),
        sa.Column("size_unit", sa.String(length=10), nullable=True),
        sa.Column("image_url", sa.Text(), nullable=True),
        sa.Column("seller_name", sa.String(length=200), nullable=True),
        sa.Column("price_bani", sa.Integer(), nullable=False),
        sa.Column("old_price_bani", sa.Integer(), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("in_stock", sa.Boolean(), nullable=False),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "old_price_bani IS NULL OR old_price_bani >= 0",
            name=op.f("ck_offers_old_price_non_negative"),
        ),
        sa.CheckConstraint("price_bani >= 0", name=op.f("ck_offers_price_non_negative")),
        sa.CheckConstraint(
            "size_value IS NULL OR size_value > 0", name=op.f("ck_offers_size_value_positive")
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_offers_product_id_products"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["retailer_id"],
            ["retailers.id"],
            name=op.f("fk_offers_retailer_id_retailers"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_offers")),
        sa.UniqueConstraint("retailer_id", "url", name="uq_offers_retailer_id_url"),
    )
    with op.batch_alter_table("offers", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_offers_ean"), ["ean"], unique=False)
        batch_op.create_index(batch_op.f("ix_offers_product_id"), ["product_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_offers_retailer_id"), ["retailer_id"], unique=False)

    op.create_table(
        "price_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("offer_id", sa.Integer(), nullable=False),
        sa.Column("price_bani", sa.Integer(), nullable=False),
        sa.Column("old_price_bani", sa.Integer(), nullable=True),
        sa.Column("in_stock", sa.Boolean(), nullable=False),
        sa.Column("scraped_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "old_price_bani IS NULL OR old_price_bani >= 0",
            name=op.f("ck_price_history_old_price_non_negative"),
        ),
        sa.CheckConstraint("price_bani >= 0", name=op.f("ck_price_history_price_non_negative")),
        sa.ForeignKeyConstraint(
            ["offer_id"],
            ["offers.id"],
            name=op.f("fk_price_history_offer_id_offers"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_price_history")),
    )
    with op.batch_alter_table("price_history", schema=None) as batch_op:
        batch_op.create_index(
            "ix_price_history_offer_id_scraped_at", ["offer_id", "scraped_at"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("price_history", schema=None) as batch_op:
        batch_op.drop_index("ix_price_history_offer_id_scraped_at")

    op.drop_table("price_history")
    with op.batch_alter_table("offers", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_offers_retailer_id"))
        batch_op.drop_index(batch_op.f("ix_offers_product_id"))
        batch_op.drop_index(batch_op.f("ix_offers_ean"))

    op.drop_table("offers")
    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_products_normalized_name"))
        batch_op.drop_index(batch_op.f("ix_products_brand_id"))

    op.drop_table("products")
    op.drop_table("retailers")
    op.drop_table("brands")
    # ### end Alembic commands ###
