"""match candidates review table

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-26 02:21:28.037525

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0002"
down_revision: str | Sequence[str] | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "match_candidates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("offer_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("reason", sa.String(length=500), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('pending', 'approved', 'rejected')",
            name=op.f("ck_match_candidates_status_known"),
        ),
        sa.CheckConstraint(
            "score >= 0 AND score <= 100", name=op.f("ck_match_candidates_score_range")
        ),
        sa.ForeignKeyConstraint(
            ["offer_id"],
            ["offers.id"],
            name=op.f("fk_match_candidates_offer_id_offers"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_match_candidates_product_id_products"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_match_candidates")),
        sa.UniqueConstraint(
            "offer_id", "product_id", name="uq_match_candidates_offer_id_product_id"
        ),
    )
    with op.batch_alter_table("match_candidates", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_match_candidates_offer_id"), ["offer_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_match_candidates_product_id"), ["product_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_match_candidates_status"), ["status"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("match_candidates", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_match_candidates_status"))
        batch_op.drop_index(batch_op.f("ix_match_candidates_product_id"))
        batch_op.drop_index(batch_op.f("ix_match_candidates_offer_id"))

    op.drop_table("match_candidates")
    # ### end Alembic commands ###
