"""retailer crawl schedule

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-26 02:38:06.840344

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0003"
down_revision: str | Sequence[str] | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("retailers", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("crawl_interval_hours", sa.Integer(), server_default="24", nullable=False)
        )
        batch_op.add_column(sa.Column("last_crawled_at", sa.DateTime(timezone=True), nullable=True))
        # Not detected by autogenerate; added by hand.
        batch_op.create_check_constraint(
            op.f("ck_retailers_crawl_interval_positive"), "crawl_interval_hours > 0"
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("retailers", schema=None) as batch_op:
        batch_op.drop_constraint(op.f("ck_retailers_crawl_interval_positive"), type_="check")
        batch_op.drop_column("last_crawled_at")
        batch_op.drop_column("crawl_interval_hours")

    # ### end Alembic commands ###
