"""offer missed runs

Revision ID: 0004
Revises: 0003
Create Date: 2026-09-26 02:41:08.653174

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0004"
down_revision: str | Sequence[str] | None = "0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("offers", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("missed_runs", sa.Integer(), server_default="0", nullable=False)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("offers", schema=None) as batch_op:
        batch_op.drop_column("missed_runs")

    # ### end Alembic commands ###
